### ISSUE TITLE
Plugin error  'Test Data Supplier' (version '0.2.9')

### ISSUE THREAD

**Issue by rgparis** [sskorol/test-data-supplier-plugin#12]
With the latest IntelliJ installed 2021.1 I received this error:
Plugin 'Test Data Supplier' (version '0.2.9') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is IU-211.6693.111

Hope this helps and hope to enjoy an update soon.

**Comment by sskorol** [comment]
I've just uploaded a new version. Should appear after JB approval. It may take up to 2 business days though. If it's urgent, I can send you an archive for a local installation.

**Comment by sskorol** [comment]
@rgparis a new 0.3.0 version is already available in JB marketplace.
